# Hotel data batch A — loaded by tools/gen_hotel_pages.py (exports HOTELS = [...]).
# Voice: firsthand entries mine the site's own reviews (athens.html, milos.html,
# sifnos.html, paros.html, mykonos.html, montenegro.html, greece-collection.html,
# sample-itinerary.html). Advisor-voice entries (not visited, or no firsthand text
# on the site) set know_heading + cta_line and never claim a stay.
#
# NO_IMAGE: white-pebble-suites-milos (milos.html points at whitepebble-1.jpg which
#   does not exist in images/hotels/ — using Milos scenic fallback from images/islands/)
# NO_IMAGE: jupiter-villa-paros (no villa photo in repo — Paros scenic fallback)
# NO_IMAGE: one-and-only-kea (no Kea photo in repo — Cyclades scenic fallback)
# NO_IMAGE: one-and-only-aesthesis-athens-riviera (no hotel photo — Athens scenic fallback)
# NO_IMAGE: one-and-only-portonovi-montenegro (no hotel photo — Montenegro coast scenic fallback)

ADVISOR_HEADING = "The Fine Print, From Your Advisor"

HOTELS = [

    # ------------------------------------------------------------------ ATHENS
    dict(
        slug="the-dolli-athens", name="The Dolli", short_name="The Dolli",
        island="Athens", island_page="athens.html", locale="Athens, Greece",
        img_dir="hotels", hero_img="thedolli-1.jpg", img2="thedolli-2.jpg",
        meta_desc="Keith's firsthand review of The Dolli in Athens — a restored neoclassical mansion with the city's most beautiful Acropolis view and one of Europe's most spectacular rooftop pools.",
        tagline="The city's most beautiful view &mdash; a restored neoclassical mansion staring straight at the Acropolis.",
        style_label="Restored neoclassical mansion", perfect_for="Design lovers, couples, first-time Athens",
        credit_label="hotel credit", partner_clause="", visited_verb="stayed at",
        region_label="City",
        stat1_num="From $900", stat1_label="Per Night, Booked Through Me",
        stat2_num="Rooftop", stat2_label="Pool Facing The Parthenon",
        rank_href="athens.html", rank_text="Featured in my Athens guide",
        related_text="Read My Full Athens Guide",
        cta2_href="greece-collection.html", cta2_text="The Greece Collection",
        cta_island_text="My Athens Guide",
        intro=[
            "Few hotels have transformed Athens' luxury scene like The Dolli. Housed inside a restored neoclassical mansion overlooking the Acropolis, it blends residential elegance with impeccable service and one of the most spectacular rooftop pools in Europe.",
            "Every space feels thoughtfully curated, making it as much a design destination as it is a hotel. If someone asks me where to splurge in Athens, The Dolli is usually my first answer &mdash; between the rooftop, the location, and the design, it's one of the most memorable hotel experiences in Greece.",
            "It's also where I start my own Athens itineraries: day one of my three perfect days in the city ends with rooftop cocktails overlooking the Parthenon, and on my sample honeymoon itinerary the welcome dinner happens on this exact rooftop.",
        ],
        stood_out=[
            ("The rooftop is reason enough to slow down.", "Whether it's cocktails before dinner or a leisurely breakfast the next morning, The Dolli's view of the illuminated Parthenon is worth saving a whole evening for."),
            ("The Acropolis Junior Suite is the room I'd book.", "Wake up to uninterrupted views of the Parthenon from one of the city's most coveted addresses."),
            ("A design destination in its own right.", "The restored mansion feels residential and curated everywhere you look &mdash; this is where I send design lovers first."),
        ],
        know=[
            ("It's a city splurge, not a resort.", "Rates start around $900 a night. If you want beach and resort grounds, pair it with <a href=\"four-seasons-astir-palace-athens.html\">Four Seasons Astir Palace</a> on the Riviera."),
            ("Give Athens at least two full days.", "Don't rush through on your way to the islands &mdash; the city has some of Greece's best hotels, restaurants, and cultural experiences."),
            ("Eat beyond the tourist center.", "I had my favorite gyros in all of Greece in Kallithea, a short taxi from the hotel &mdash; a reminder that Athens' best food is found well beyond Plaka."),
        ],
        verdict="If someone asks me where to splurge in Athens, The Dolli is usually my first answer.",
    ),

    dict(
        slug="four-seasons-astir-palace-athens", name="Four Seasons Astir Palace", short_name="Astir Palace",
        island="Athens", island_page="athens.html", locale="Athens Riviera, Greece",
        img_dir="hotels", hero_img="astirpalace-1.jpg", img2="astirpalace-2.jpg",
        meta_desc="Keith's firsthand review of Four Seasons Astir Palace on the Athens Riviera — a private peninsula resort with beaches, Michelin-starred dining, and the Acropolis thirty minutes away.",
        tagline="Where Athens meets the sea &mdash; a private peninsula that feels like two vacations in one.",
        style_label="Seaside urban resort", perfect_for="Families, beach lovers, celebrations, extended stays",
        credit_label="hotel credit", partner_clause="", visited_verb="visited",
        region_label="Region",
        stat1_num="30 min", stat1_label="From The Acropolis",
        stat2_num="From $1,300", stat2_label="Per Night, Booked Through Me",
        rank_href="athens.html", rank_text="Featured in my Athens guide",
        related_text="Read My Full Athens Guide",
        cta2_href="greece-collection.html", cta2_text="The Greece Collection",
        cta_island_text="My Athens Guide",
        intro=[
            "Four Seasons Astir Palace proves Athens isn't just a city destination. Set along a private peninsula overlooking the Saronic Gulf, it combines world-class dining, multiple beaches, and resort-style luxury just thirty minutes from the Acropolis.",
            "It's the perfect balance of city access and a true seaside escape &mdash; spend your mornings by the sea, your afternoons exploring Athens, and return each evening to one of Europe's finest urban resorts.",
            "It's the hotel I build day two of my Athens itinerary around: a day along the Riviera, a long seaside lunch, a stroll through Astir Marina, and dinner overlooking the Saronic Gulf. On my sample honeymoon itinerary, this is where my clients land first.",
        ],
        stood_out=[
            ("The private coves deserve more than a quick swim.", "Astir's beach club is one of the Riviera's biggest advantages &mdash; spend a full afternoon there."),
            ("Pelagos is worth planning your evening around.", "One of the best Michelin-starred meals in Greece, right on property. Manko is the other table I send clients to on the peninsula."),
            ("The Sea View Bungalow Suite is the room I'd book.", "Privacy, generous outdoor space, and direct access to the Riviera lifestyle."),
        ],
        know=[
            ("It's a resort first, a city base second.", "If your trip is museums and rooftops, stay at <a href=\"the-dolli-athens.html\">The Dolli</a> instead &mdash; or better, split the stay and do both."),
            ("Explore Vouliagmeni.", "Walk to the lake or enjoy dinner in town before returning to the calm of the peninsula."),
            ("Few hotels balance city and beach this effortlessly.", "That makes it ideal for families and longer stays where one member of the party wants beach days and another wants the Acropolis."),
        ],
        verdict="Astir Palace feels like two vacations in one &mdash; few hotels balance city and beach this effortlessly.",
    ),

    # ------------------------------------------------------------------- MILOS
    dict(
        slug="skinopi-lodge-milos", name="Skinopi Lodge", short_name="Skinopi Lodge",
        island="Milos", island_page="milos.html", locale="Milos, Greece",
        img_dir="hotels", hero_img="skinopi-1.jpg", img2="skinopi-2.jpg",
        meta_desc="Keith's firsthand review of Skinopi Lodge on Milos — traditional architecture, modern simplicity, and sweeping sea views above the Aegean near Klima.",
        tagline="Above the Aegean &mdash; traditional architecture and modern simplicity in one of Milos' most unique boutique stays.",
        style_label="Boutique hillside lodge", perfect_for="Couples, design lovers, privacy, nature",
        credit_label="hotel credit", partner_clause="", visited_verb="visited",
        region_label="Island",
        stat1_num="From $750", stat1_label="Per Night, Booked Through Me",
        stat2_num="Minutes", stat2_label="From The Village Of Klima",
        rank_href="milos.html", rank_text="Featured in my Milos guide",
        related_text="Read My Full Milos Guide",
        cta2_href="greece-collection.html", cta2_text="The Greece Collection",
        cta_island_text="My Milos Guide",
        intro=[
            "Perched above the sea, Skinopi Lodge blends traditional architecture with modern simplicity. Every detail feels intentional, creating one of Milos' most unique boutique stays for travelers seeking authenticity over excess.",
            "Skinopi isn't trying to compete with Milos' dramatic landscapes &mdash; it complements them. The architecture blends seamlessly into the hillside, the pace is intentionally slow, and the setting makes it one of those rare hotels where returning each afternoon becomes part of the experience.",
            "The location is also quietly strategic: Klima is only a few minutes away for a pre-dinner wander, and the lodge is perfectly positioned for exploring Milos' western coastline by boat before the crowds arrive.",
        ],
        stood_out=[
            ("Villa Almyra is the room I'd book.", "A beautifully restored retreat with sweeping sea views."),
            ("The quiet setting is the point.", "Uninterrupted sea views and a deliberately slow pace &mdash; reason enough not to leave every night."),
            ("Perfectly positioned for the water.", "Book a boat for the next morning and see the western coastline before anyone else does."),
        ],
        know=[
            ("This is authenticity over excess.", "If you want a full resort with restaurants and a spa, look at <a href=\"erema-milos.html\">Er&#275;ma</a> instead."),
            ("Head into Klima before sunset.", "It's only a few minutes away and one of the best places on the island to wander before dinner."),
            ("Milos rewards a slower itinerary.", "Give the island three nights and build in a private boat day &mdash; my <a href=\"../milos.html\">Milos guide</a> maps out exactly how I'd do it."),
        ],
        verdict="One of those rare hotels where returning each afternoon becomes part of the experience.",
    ),

    dict(
        slug="erema-milos", name="Er&#275;ma, a Member of Design Hotels", short_name="Er&#275;ma",
        island="Milos", island_page="milos.html", locale="Milos, Greece",
        img_dir="hotels", hero_img="erema-1.jpg", img2="erema-2.jpg",
        meta_desc="Keith's firsthand review of Erēma on Milos — contemporary Cycladic architecture, expansive suites, and a private-estate feel minutes from the island's best beaches.",
        tagline="A private island feeling &mdash; one of Milos' newest luxury hotels, more private estate than traditional resort.",
        style_label="Contemporary Cycladic estate", perfect_for="Couples, design lovers, privacy, luxury escapes",
        credit_label="hotel credit", partner_clause="", visited_verb="visited",
        region_label="Island",
        stat1_num="From $900", stat1_label="Per Night, Booked Through Me",
        stat2_num="Cosme &amp; Par&#299;lio", stat2_label="Sister Properties On Paros",
        rank_href="milos.html", rank_text="Featured in my Milos guide",
        related_text="Read My Full Milos Guide",
        cta2_href="cosme-vs-parilio-paros.html", cta2_text="Cosme vs. Par&#299;lio, Compared",
        cta_island_text="My Milos Guide",
        intro=[
            "One of Milos' newest luxury hotels, Er&#275;ma feels more like a private estate than a traditional resort. Contemporary Cycladic architecture, expansive suites, and a secluded setting create a stay that's peaceful, design-forward, and just minutes from some of the island's best beaches.",
            "Er&#275;ma feels refreshingly understated. If you're looking for contemporary design, genuine privacy, and a slower side of Milos, it's one of the island's strongest luxury stays.",
            "It comes from the same group behind Cosme and Par&#299;lio on Paros &mdash; and it's the newest of the three, the one nobody has posted to death yet. Paros then Milos is the trip I'd actually book, and a private boat or helicopter between the two takes the hard part out of it.",
        ],
        stood_out=[
            ("The Horizon Suite with Private Pool is the room I'd book.", "Expansive indoor-outdoor living with uninterrupted Aegean views and exceptional privacy."),
            ("The private-estate feel.", "Secluded, quiet, and design-forward &mdash; a genuine rarity among new Cycladic openings."),
            ("The pedigree.", "Same group as Cosme and Par&#299;lio on Paros &mdash; my <a href=\"../cosme-vs-parilio-paros.html\">comparison of the two</a> explains why that matters."),
        ],
        know=[
            ("Stay at least three nights.", "Milos deserves more than a quick stop, and Er&#275;ma is best enjoyed at a slower pace."),
            ("Pair your stay with a private boat day.", "Seeing Milos from the water completely changes the experience, and Er&#275;ma makes the perfect base."),
            ("Plan beach time into your itinerary.", "The hotel feels wonderfully secluded, but some of Milos' best beaches are only a short drive away."),
            ("Can't choose between Cosme and Par&#299;lio?", "The better question is whether you should be doing two islands instead of one &mdash; Paros then Milos, ending here."),
        ],
        verdict="Refreshingly understated — one of the island's strongest luxury stays for design, privacy, and the slower side of Milos.",
    ),

    dict(
        slug="white-pebble-suites-milos", name="White Pebble Suites", short_name="White Pebble",
        island="Milos", island_page="milos.html", locale="Milos, Greece",
        img_dir="islands", hero_img="milos-hero.jpg", img2="milos-divider.jpg",
        meta_desc="Keith's firsthand review of White Pebble Suites on Milos — contemporary Cycladic design perched above the waterfront village of Pollonia.",
        tagline="Seaside elegance above Pollonia &mdash; contemporary Cycladic design in one of Milos' most charming villages.",
        style_label="Boutique village hotel", perfect_for="Couples, boutique luxury, design lovers",
        credit_label="hotel credit", partner_clause="", visited_verb="visited",
        region_label="Island",
        stat1_num="From $850", stat1_label="Per Night, Booked Through Me",
        stat2_num="Pollonia", stat2_label="Restaurants Within Walking Distance",
        rank_href="milos.html", rank_text="Featured in my Milos guide",
        related_text="Read My Full Milos Guide",
        cta2_href="greece-collection.html", cta2_text="The Greece Collection",
        cta_island_text="My Milos Guide",
        intro=[
            "White Pebble Suites pairs contemporary Cycladic design with one of Milos' best locations. Perched above the waterfront village of Pollonia, it offers understated luxury, personalized service, and easy walking access to the island's best restaurants, caf&eacute;s, and seaside promenade.",
            "It's a polished boutique experience in one of Milos' most charming villages. If you're looking for contemporary luxury with easy access to Pollonia's restaurants and waterfront, it's an excellent base for exploring the island.",
            "Pollonia itself becomes part of the stay: walk into the village every evening, settle into the slower rhythm of the waterfront, and use the harbor as your launch point for the rest of the island.",
        ],
        stood_out=[
            ("The Honeymoon Suite is the room I'd book.", "Beautiful sea views with the simplicity and understated design that define White Pebble."),
            ("The location does half the work.", "Some of Milos' best restaurants are a short stroll away &mdash; the village is the amenity."),
            ("The easiest day trip in the Cyclades.", "Pollonia is the departure point for the ferry to Kimolos, a perfect low-effort day out."),
        ],
        know=[
            ("This is a village hotel, not a secluded estate.", "If total privacy is the priority, look at <a href=\"erema-milos.html\">Er&#275;ma</a> or <a href=\"skinopi-lodge-milos.html\">Skinopi Lodge</a> instead."),
            ("Walk into Pollonia every evening.", "The restaurants and promenade are the reason to stay here &mdash; use them."),
            ("Save an afternoon for the waterfront.", "Grab a drink, wander the promenade, and settle into the slower rhythm that makes Pollonia so appealing."),
        ],
        verdict="A polished boutique experience in one of Milos' most charming villages — an excellent base for exploring the island.",
    ),

    # ------------------------------------------------------------------ SIFNOS
    dict(
        slug="nos-sifnos", name="NOS", short_name="NOS",
        island="Sifnos", island_page="sifnos.html", locale="Sifnos, Greece",
        img_dir="hotels", hero_img="nos-1.jpg", img2="nos-2.jpg",
        meta_desc="Keith's firsthand review of NOS on Sifnos — minimalist Cycladic architecture and sweeping Aegean views above the fishing village of Faros.",
        tagline="Seaside simplicity above Faros &mdash; one of Sifnos' most thoughtfully designed boutique hotels.",
        style_label="Minimalist boutique hotel", perfect_for="Adults, quiet luxury, design lovers, wellness",
        credit_label="hotel credit", partner_clause="", visited_verb="visited",
        region_label="Island",
        stat1_num="From $700", stat1_label="Per Night, Booked Through Me",
        stat2_num="Faros", stat2_label="Waterfront Tavernas A Walk Away",
        rank_href="sifnos.html", rank_text="Featured in my Sifnos guide",
        related_text="Read My Full Sifnos Guide",
        cta2_href="greece-collection.html", cta2_text="The Greece Collection",
        cta_island_text="My Sifnos Guide",
        intro=[
            "NOS is one of Sifnos' most thoughtfully designed boutique hotels. Set above the fishing village of Faros, it pairs minimalist Cycladic architecture, sweeping Aegean views, and an atmosphere that feels effortlessly calm.",
            "NOS isn't trying to impress with excess. Everything feels intentional, from the architecture to the pace of the experience. If you're looking for a hotel that feels deeply connected to Sifnos rather than separate from it, this is one of my favorite stays in the Cyclades.",
            "Sifnos is my pick for the most underrated island in Greece &mdash; the island where Greece slows down &mdash; and NOS matches that rhythm exactly.",
        ],
        stood_out=[
            ("Wake up for sunrise.", "The east-facing views make early mornings one of the most memorable parts of staying here."),
            ("The Faros Superior is the room I'd book.", "Sun-washed interiors, generous indoor-outdoor living, and the effortless simplicity that defines NOS."),
            ("An afternoon of doing nothing.", "NOS is one of the few hotels where lingering by your suite feels just as rewarding as exploring the island."),
        ],
        know=[
            ("This is quiet luxury, deliberately.", "Adults, design lovers, and wellness travelers will love it; anyone chasing scene and nightlife should look at Mykonos instead."),
            ("Walk into Faros for dinner.", "The fishing village feels refreshingly untouched, with some of Sifnos' best waterfront tavernas."),
            ("Sifnos asks you to linger.", "Some islands ask you to see more &mdash; this one doesn't. Build your itinerary accordingly, and my <a href=\"../sifnos.html\">Sifnos guide</a> shows how."),
        ],
        verdict="A hotel that feels deeply connected to Sifnos rather than separate from it — one of my favorite stays in the Cyclades.",
    ),

    # ------------------------------------------------------------------- PAROS
    dict(
        slug="andronis-minois-paros", name="Andronis Minois", short_name="Andronis Minois",
        island="Paros", island_page="paros.html", locale="Paros, Greece",
        img_dir="hotels", hero_img="andronis-minois-1.jpg", img2="andronis-minois-2.jpg",
        meta_desc="Keith's firsthand review of Andronis Minois on Paros — generous suites, thoughtful service, and a relaxed resort atmosphere away from the island's busiest villages.",
        tagline="A modern island escape &mdash; the relaxed side of Paros, with space to truly unwind.",
        style_label="Relaxed luxury resort", perfect_for="Families, couples, longer stays, resort lovers",
        credit_label="hotel credit", partner_clause="", visited_verb="visited",
        region_label="Island",
        stat1_num="From $700", stat1_label="Per Night, Booked Through Me",
        stat2_num="Shuttle", stat2_label="Complimentary Ride To Naousa",
        rank_href="paros.html", rank_text="Featured in my Paros guide",
        related_text="Read My Full Paros Guide",
        cta2_href="greece-collection.html", cta2_text="The Greece Collection",
        cta_island_text="My Paros Guide",
        intro=[
            "Andronis Minois offers a more relaxed side of Paros. Tucked away from the island's busiest villages, it combines generous suites, thoughtful service, and a peaceful atmosphere that's ideal for travelers seeking space to truly unwind.",
            "For travelers who prioritize space, comfort, and a true resort atmosphere, Andronis Minois delivers one of the island's most relaxing luxury stays.",
            "The slower pace rewards travelers who aren't in a hurry &mdash; this is a stay-four-nights property, not a one-night stopover, and Paros is my pick for the best island in Greece for return visitors.",
        ],
        stood_out=[
            ("The Minois Blu Suite Sea View is the room I'd book.", "One of the property's most spacious accommodations, with panoramic sea views and room to truly settle in."),
            ("The complimentary shuttle.", "An easy way to enjoy Naousa for dinner without worrying about parking or driving home."),
            ("Space, in every sense.", "Generous suites and a peaceful setting away from the island's busiest villages."),
        ],
        know=[
            ("Stay for at least four nights.", "The slower pace rewards travelers who aren't in a hurry."),
            ("Explore Aliki.", "The charming fishing village is just minutes away and one of my favorite spots for a leisurely seafood lunch by the water."),
            ("Weigh it against the design hotels.", "If design is your priority over resort space, compare <a href=\"vione-paros.html\">Vione</a> and my <a href=\"../cosme-vs-parilio-paros.html\">Cosme vs. Par&#299;lio breakdown</a> before booking."),
        ],
        verdict="For travelers who prioritize space, comfort, and a true resort atmosphere, one of the island's most relaxing luxury stays.",
    ),

    dict(
        slug="vione-paros", name="Vione", short_name="Vione",
        island="Paros", island_page="paros.html", locale="Paros, Greece",
        img_dir="hotels", hero_img="vione-1.jpg", img2="vione-2.jpg",
        meta_desc="Keith's firsthand review of Vione on Paros — clean architecture, understated interiors, and the most expansive spa he saw in the Cyclades.",
        tagline="A modern Paros retreat &mdash; intimate, understated, and effortlessly stylish.",
        style_label="Adults-focused boutique hotel", perfect_for="Adults, design lovers, couples, wellness",
        credit_label="hotel credit", partner_clause="", visited_verb="visited",
        region_label="Island",
        stat1_num="From $800", stat1_label="Per Night, Booked Through Me",
        stat2_num="Spa", stat2_label="The Most Expansive I Saw In The Cyclades",
        rank_href="paros.html", rank_text="Featured in my Paros guide",
        related_text="Read My Full Paros Guide",
        cta2_href="greece-collection.html", cta2_text="The Greece Collection",
        cta_island_text="My Paros Guide",
        intro=[
            "Vione brings a fresh perspective to luxury on Paros. Clean architecture, understated interiors, and a peaceful adults-focused atmosphere create a boutique hotel that feels intimate, modern, and effortlessly stylish.",
            "Vione is the kind of hotel that quietly impresses you. Every detail feels considered, making it an excellent choice for travelers who appreciate thoughtful design and understated luxury.",
            "The property was also featured in the Paros section of my Greece Collection travel journal &mdash; the team told me they were honored to be included, and it's the kind of hotel that earns that place quietly rather than loudly.",
        ],
        stood_out=[
            ("The spa was the most expansive I saw in the Cyclades.", "Leave real time for it &mdash; wellness is a genuine strength here, not an afterthought."),
            ("The Jr Suite with Private Pool is the room I'd book.", "Minimalist interiors paired with uninterrupted views of the Aegean."),
            ("The Junior Suites are a sneaky value.", "Surprisingly spacious, with more than enough room for a special stay &mdash; one of the property's best values."),
        ],
        know=[
            ("It's adults-focused by design.", "Traveling with kids? <a href=\"andronis-minois-paros.html\">Andronis Minois</a> is my family pick on Paros."),
            ("Balance hotel time with exploring Naousa.", "You'll appreciate returning to Vione's quiet atmosphere after a day on the island."),
            ("Paros is my best island for return visitors.", "It's also the island I keep thinking about &mdash; my <a href=\"../paros.html\">Paros guide</a> covers how I'd structure the whole stay."),
        ],
        verdict="The kind of hotel that quietly impresses you — every detail feels considered.",
    ),

    dict(
        slug="jupiter-villa-paros", name="Jupiter", short_name="Jupiter",
        island="Paros", island_page="paros.html", locale="Paros, Greece",
        img_dir="islands", hero_img="paros-hero.jpg", img2="paros-divider.jpg",
        meta_desc="Why Keith names Jupiter, a five-bedroom villa on Paros, the Best Paros Villa in his Greece Collection — and how he books villa trips around it.",
        tagline="My pick for the best villa on Paros &mdash; a five-bedroom base for the island I keep thinking about.",
        style_label="Private five-bedroom villa", perfect_for="Families, groups, villa buyout trips",
        credit_label="hotel credit", partner_clause="", visited_verb="reviewed",
        region_label="Island",
        know_heading=ADVISOR_HEADING,
        cta_line="Jupiter is on my booking list for a reason. Let me confirm the right dates, staff it properly, and build the rest of the Paros trip around it.",
        stat1_num="Best Paros Villa", stat1_label="In My Greece Collection Edit",
        stat2_num="5", stat2_label="Bedrooms",
        rank_href="greece-collection.html", rank_text="Best Paros Villa, The Greece Collection",
        related_text="See The Full Greece Collection Edit",
        cta2_href="paros.html", cta2_text="My Paros Guide",
        cta_island_text="My Paros Guide",
        intro=[
            "When I put together the awards edit for my Greece Collection, one villa took the Paros category outright: Jupiter, a five-bedroom villa that I named Best Paros Villa.",
            "The reason it's on my list is simple &mdash; Paros is my pick for the best island in Greece for return visitors, and it's the island I keep thinking about. For a family or group that wants a private base rather than a hotel, a villa of this caliber changes how the whole trip works.",
            "Villa trips are a different kind of booking: staffing, provisioning, boat days, and dinner reservations all need to be arranged around the house rather than a concierge desk. That's exactly the part I handle.",
        ],
        stood_out=[
            ("It won my Best Paros Villa award.", "Out of everything I evaluated for the Greece Collection's Paros section, this is the villa I named first."),
            ("Five bedrooms changes the math.", "For a multi-family trip or a group celebration, a full villa often beats booking a row of suites &mdash; in both privacy and experience."),
            ("Paros is built for the villa format.", "Naousa's restaurants, the beaches, and the boat days all work beautifully from a private base."),
        ],
        know=[
            ("Villas book differently than hotels.", "Peak weeks go early and minimum-stay rules apply &mdash; talk to me before you lock flights."),
            ("Prefer a hotel instead?", "My hotel picks on the island are <a href=\"vione-paros.html\">Vione</a> and <a href=\"andronis-minois-paros.html\">Andronis Minois</a> &mdash; and my <a href=\"../cosme-vs-parilio-paros.html\">Cosme vs. Par&#299;lio</a> piece covers the design-hotel route."),
            ("Pair it with a boat day.", "Seeing the Cyclades from the water is the upgrade every villa group thanks me for later."),
        ],
        verdict="My Best Paros Villa — the private base I book for groups on the island I keep thinking about.",
    ),

    # ----------------------------------------------------------------- MYKONOS
    dict(
        slug="fouquets-mykonos", name="Fouquet's Mykonos", short_name="Fouquet's",
        island="Mykonos", island_page="mykonos.html", locale="Mykonos, Greece",
        img_dir="hotels", hero_img="fouquets-1.jpg", img2="fouquets-2.jpg",
        meta_desc="Keith's firsthand review of Fouquet's Mykonos — his Best New Resort in Greece, walking distance from Paraga Beach and Scorpios with standout dining at ZUMA.",
        tagline="Mykonos' most exciting new resort &mdash; and my pick for Best New Resort in Greece.",
        style_label="South-coast luxury resort", perfect_for="Luxury travelers, couples, groups, celebrations",
        credit_label="hotel credit", partner_clause="", visited_verb="toured and returned to",
        region_label="Island",
        stat1_num="Best New Resort", stat1_label="In My Greece Collection Edit",
        stat2_num="From $900", stat2_label="Per Night, Booked Through Me",
        rank_href="greece-collection.html", rank_text="Best New Resort, The Greece Collection",
        related_text="See The Full Greece Collection Edit",
        cta2_href="already-booked-mykonos.html", cta2_text="Already Booked Mykonos? Start Here",
        cta_island_text="My Mykonos Guide",
        intro=[
            "Fouquet's brings the energy of Mykonos' south coast together with the comfort of a true luxury resort. Spacious accommodations, standout dining, and polished service make it an ideal base for travelers who want both beach clubs and resort time.",
            "I had the opportunity to tour the property while it was still under construction, so returning after it opened was especially rewarding &mdash; the finished resort exceeded even those early expectations. In my Greece Collection edit, I named it Best New Resort.",
            "It's one of my favorite recommendations for travelers who want the energy of Mykonos' south coast without sacrificing the comforts of a true luxury resort.",
        ],
        stood_out=[
            ("Dinner at ZUMA.", "One of the strongest dining experiences on Mykonos and worth planning an evening around, even if you're staying elsewhere."),
            ("The underground sports court.", "A massive subterranean basketball court that's unlike anything you'll find at most luxury resorts."),
            ("Walk to Paraga Beach or Scorpios.", "Being able to leave the car behind is one of the hotel's biggest advantages."),
            ("The Aegean Suite with Private Pool is the room I'd book.", "Expansive outdoor living with one of the property's best balances of privacy, space, and sea views."),
        ],
        know=[
            ("It's on the energetic side of the island.", "That's the point &mdash; if you want quiet beachfront instead, look at <a href=\"bill-and-coo-suites-mykonos.html\">Bill &amp; Coo</a>."),
            ("Book beach clubs before you land.", "Scorpios and the south-coast clubs fill up &mdash; my <a href=\"../already-booked-mykonos.html\">already-booked Mykonos page</a> covers the reservations worth making now."),
            ("New-build polish, real resort comforts.", "The finished property exceeded the expectations I formed touring it under construction &mdash; that almost never happens."),
        ],
        verdict="The energy of Mykonos' south coast with the comforts of a true luxury resort — my Best New Resort in Greece.",
    ),

    dict(
        slug="bill-and-coo-suites-mykonos", name="Bill &amp; Coo Suites", short_name="Bill &amp; Coo Suites",
        island="Mykonos", island_page="mykonos.html", locale="Mykonos, Greece",
        img_dir="hotels", hero_img="billandcoo-coast-1.jpg", img2="billandcoo-coast-2.jpg",
        meta_desc="Keith's review of Bill & Coo Suites near Mykonos Town — winner of Best Breakfast and Best Service in his Greece Collection edit.",
        tagline="The best breakfast in Greece, from the hotel group with the best service on Mykonos.",
        style_label="Boutique suites near Mykonos Town", perfect_for="Couples, families, food lovers, town access",
        credit_label="hotel credit", partner_clause="", visited_verb="visited",
        region_label="Island",
        stat1_num="Best Breakfast", stat1_label="In My Greece Collection Edit",
        stat2_num="Best Service", stat2_label="On Mykonos, In My Edit",
        rank_href="greece-collection.html", rank_text="Best Breakfast &amp; Best Service, The Greece Collection",
        related_text="See The Full Greece Collection Edit",
        cta2_href="already-booked-mykonos.html", cta2_text="Already Booked Mykonos? Start Here",
        cta_island_text="My Mykonos Guide",
        intro=[
            "In my Greece Collection edit, Bill &amp; Coo took two categories: Best Breakfast went to Bill &amp; Coo Suites, and Best Service on Mykonos went to the Bill &amp; Coo family as a whole. That's not an accident &mdash; this is the group that consistently out-executes the island.",
            "Bill &amp; Coo Suites is the property to consider if being closer to Mykonos Town or traveling with family is a priority. Its sister property, Bill &amp; Coo Coast, is my choice for a true beachfront stay &mdash; unlike most of Mykonos' luxury hotels perched high above the sea, the Coast brings you directly to the shoreline.",
            "Between the two, you're choosing a location, not a level of quality: exceptional dining and relaxed, genuinely warm service run through both.",
        ],
        stood_out=[
            ("The breakfast that won my award.", "Best Breakfast across every hotel in my Greece Collection edit &mdash; plan a slow morning around it."),
            ("Service that took its own category.", "Best Service on Mykonos in my edit. The team's warmth is the thread through everything the group does."),
            ("Two properties, one standard.", "Suites for town access and families; the Coast for elegant beachfront suites directly on the shoreline."),
        ],
        know=[
            ("Compare both Bill &amp; Coo properties before booking.", "The Coast is my choice for a true beachfront stay; the Suites win if Mykonos Town or family travel is the priority."),
            ("Town access is the differentiator.", "If your Mykonos is dinners, boutiques, and evenings in town, the Suites' location earns its keep every single night."),
            ("Dining is a reason to stay in.", "Exceptional restaurants across the group &mdash; and my <a href=\"../already-booked-mykonos.html\">already-booked Mykonos page</a> lists the other tables worth reserving."),
        ],
        verdict="Best Breakfast and Best Service in my Greece Collection edit — the group that consistently out-executes Mykonos.",
    ),

    # ------------------------------------------------------- ADVISOR: ONE&ONLY
    dict(
        slug="one-and-only-kea", name="One&amp;Only Kea", short_name="One&amp;Only Kea",
        island="Kea", island_page="greece-collection.html", locale="Kea, Greece",
        img_dir="islands", hero_img="cover.jpg", img2="cover-v2.jpg",
        meta_desc="Why One&Only Kea is on Keith's booking list — an honest advisor's take on the resort he hasn't yet visited, and who he books it for.",
        tagline="The One&amp;Only flag an hour from Athens &mdash; on my booking list, and next on my inspection list.",
        style_label="Resort &amp; private homes", perfect_for="Privacy seekers, One&amp;Only loyalists, Athens add-ons",
        credit_label="hotel credit", partner_clause="", visited_verb="reviewed",
        region_label="Island",
        know_heading=ADVISOR_HEADING,
        cta_line="One&amp;Only Kea is on my booking list for a reason. Let me match you to the right room, time it to the right season, and build the rest of the trip around it.",
        stat1_num="Fora", stat1_label="Preferred Partner Perks",
        stat2_num="38", stat2_label="Greek Hotels I've Personally Vetted",
        rank_href="best-hotels-greece.html", rank_text="See my Greece Top 10",
        related_text="See My 10 Favorite Hotels In Greece",
        cta2_href="best-hotels-greece.html", cta2_text="My 10 Favorite Hotels In Greece",
        cta_island_text="The Greece Collection",
        intro=[
            "Full transparency, because it's how I work: I haven't visited One&amp;Only Kea yet. When I spent four weeks in Greece visiting 38 hotels across seven islands for my Greece Collection, Kea wasn't on the route &mdash; and I said so plainly in my Greece rankings rather than pretending otherwise.",
            "It's on my booking list anyway, and here's why: it's the One&amp;Only flag in the Greek islands, on an island most itineraries skip, which is exactly the combination my privacy-focused clients ask me for. Kea sits close to Athens, which makes it a natural pairing with a city stay at <a href=\"the-dolli-athens.html\">The Dolli</a> or a Riviera stretch at <a href=\"four-seasons-astir-palace-athens.html\">Astir Palace</a>.",
            "When I book a property I haven't yet walked myself, my clients still get the full advisor layer: Fora preferred partner amenities, my vetting calls with the on-property team before arrival, and a direct line to me throughout the stay.",
        ],
        stood_out=[
            ("Why it's on my list.", "A true resort brand's take on a quiet island &mdash; the kind of privacy-first booking my Cyclades-fatigued clients ask for."),
            ("The Athens pairing.", "Kea's proximity to the mainland makes it one of the easiest luxury island add-ons to an Athens itinerary."),
            ("The advisor layer travels with you.", "Preferred partner perks and my pre-arrival call with the team on property, whether or not I've slept in the bed yet."),
        ],
        know=[
            ("I haven't inspected it yet.", "My Greece Top 10 is built only from properties I've personally experienced &mdash; that's why Kea isn't ranked there, and why I'm telling you rather than hiding it."),
            ("Getting there is different.", "Kea isn't on the main Cyclades ferry spine &mdash; routing matters, and my <a href=\"../greek-ferry-rules.html\">Greek ferry rules</a> explain why I plan crossings before dates."),
            ("Want only firsthand-vetted picks?", "Start with my <a href=\"../best-hotels-greece.html\">10 favorite hotels in Greece</a> &mdash; every one of them I've walked myself."),
        ],
        verdict="On my booking list today, on my inspection list next — and I'll tell you plainly which side of that line it's on.",
    ),

    dict(
        slug="one-and-only-aesthesis-athens", name="One&amp;Only Aesthesis", short_name="Aesthesis",
        island="Athens Riviera", island_page="athens.html", locale="Athens Riviera, Greece",
        img_dir="islands", hero_img="athens-hero.jpg", img2="athens-divider.jpg",
        mailto_prep="on the",
        meta_desc="Why Keith books One&Only Aesthesis on the Athens Riviera — the resort behind the Mãnko Beach cabana day he writes into his honeymoon itineraries.",
        tagline="The Riviera resort behind the M&atilde;nko Beach day I write into my Athens itineraries.",
        style_label="Riviera beach resort", perfect_for="Beach days, honeymoon starts, Riviera loyalists",
        credit_label="hotel credit", partner_clause="", visited_verb="reviewed",
        region_label="Region",
        know_heading=ADVISOR_HEADING,
        cta_line="Aesthesis is on my booking list for a reason. Let me match you to the right room, time it to the right season, and build the rest of the trip around it.",
        stat1_num="Fora", stat1_label="Preferred Partner Perks",
        stat2_num="M&atilde;nko", stat2_label="The Beach Day In My Sample Itinerary",
        rank_href="athens.html", rank_text="Featured in my Athens planning",
        related_text="Read My Full Athens Guide",
        cta2_href="sample-itinerary.html", cta2_text="See A Sample Itinerary",
        cta_island_text="My Athens Guide",
        intro=[
            "If you've read my sample honeymoon itinerary, you've already met One&amp;Only Aesthesis without realizing it: the cabana day at M&atilde;nko Beach that I write into the Athens leg happens here, on the Riviera coast south of the city.",
            "That's the reason it's on my list &mdash; the Athens Riviera has become a genuine luxury destination in its own right, and Aesthesis gives my clients a One&amp;Only beach day within reach of the Acropolis.",
            "I book it two ways: as the beach-day counterpoint to a city stay at <a href=\"the-dolli-athens.html\">The Dolli</a>, or as part of a full Riviera stretch alongside <a href=\"four-seasons-astir-palace-athens.html\">Four Seasons Astir Palace</a> before the islands.",
        ],
        stood_out=[
            ("The M&atilde;nko Beach cabana day.", "The exact day I write into my sample honeymoon itinerary &mdash; a Riviera beach afternoon before a rooftop dinner in the city."),
            ("The Riviera position.", "A true beach resort within striking distance of the Acropolis &mdash; the combination that makes Athens more than a stopover."),
            ("It plays well with others.", "Easy to pair with The Dolli in the city or Astir Palace on the peninsula for a two-hotel Athens chapter."),
        ],
        know=[
            ("Athens deserves two full days minimum.", "Don't treat the Riviera as a layover &mdash; my <a href=\"../athens.html\">Athens guide</a> lays out three perfect days including the Riviera."),
            ("Choose your Riviera flag deliberately.", "Astir Palace is the peninsula resort I've walked myself; Aesthesis is the beach-scene alternative &mdash; I'll match you to the right one."),
            ("Cabana days need booking.", "Like the island beach clubs, the good real estate at M&atilde;nko goes early in peak season &mdash; I reserve it when I confirm the room."),
        ],
        verdict="The Riviera beach day I already write into my itineraries — booked as its own stay when the trip calls for it.",
    ),

    # -------------------------------------------------------------- MONTENEGRO
    dict(
        slug="aman-sveti-stefan-montenegro", name="Aman Sveti Stefan &amp; Villa Milo&#269;er", short_name="Aman Sveti Stefan",
        island="Montenegro", island_page="montenegro.html", locale="Sveti Stefan, Montenegro",
        img_dir="montenegro", hero_img="sveti-stefan-aerial.jpg", img2="aman-sveti-stefan-indoor-pool.jpg",
        mailto_prep="in",
        meta_desc="Keith's firsthand report from Aman Sveti Stefan — touring Villa Miločer with the GM ahead of the island's reopening, from beach access to buyouts.",
        tagline="Toured firsthand with the GM ahead of the island's reopening &mdash; straight answers on beaches, suites, and buyouts.",
        style_label="Historic island resort &amp; villa", perfect_for="Couples, privacy seekers, full buyouts",
        credit_label="hotel credit", partner_clause="", visited_verb="toured",
        region_label="Country",
        stat1_num="50", stat1_label="Accommodations Across The Island",
        stat2_num="GM", stat2_label="Toured Firsthand With The General Manager",
        rank_href="montenegro.html", rank_text="Reviewed in my Montenegro guide",
        related_text="Read My Full Montenegro Guide",
        cta2_href="montenegro.html", cta2_text="Montenegro, Hotel By Hotel",
        cta_island_text="My Montenegro Guide",
        intro=[
            "I spent an afternoon at Aman Sveti Stefan touring Villa Milo&#269;er and sitting down directly with the GM ahead of the island's reopening. I work directly with the team there, and everything I share comes from that visit and that relationship &mdash; not press materials.",
            "Villa Milo&#269;er surprised me. I assumed the Garden View Suites were inside the villa, but they aren't &mdash; the one I toured is in a separate building about a two-minute walk uphill, and there are only two of them. The room was huge and far more residential than I expected: large bedroom, generous bathroom, then a hallway into a separate living and dining room. The design is exactly what you'd imagine from Aman &mdash; quiet, understated, lots of Japanese influence, nothing trying too hard.",
            "The spa was probably my favorite part of the visit: a newer building with an indoor/outdoor pool under huge vaulted timber ceilings, opening directly toward Queen's Beach &mdash; which might be the prettiest beach I've seen in Montenegro. There's now a restaurant there too, so I could easily see spending an entire afternoon between the spa, lunch, and the beach.",
        ],
        stood_out=[
            ("Queen's Beach.", "Expected to remain exclusive to Aman guests, accessed through a gated entrance &mdash; and possibly the prettiest beach I've seen in Montenegro."),
            ("The spa building.", "Vaulted timber ceilings, an indoor/outdoor pool facing Queen's Beach, and its own restaurant, reserved exclusively for hotel guests."),
            ("A refreshing photography policy.", "Aman asked that I not share my photos &mdash; no filming in public areas with guests present, no tripods, no drones. In a world of hotels built for social media, I found that pretty refreshing."),
            ("Zuma and Nammos within walking distance.", "I had lunch at Zuma after the tour &mdash; fantastic service &mdash; and having both nearby is a big improvement for four- or five-night stays."),
        ],
        know=[
            ("Island or villa? Here's my line.", "Traveling with kids, a stroller, or mobility concerns: book Villa Milo&#269;er. As a couple already spending around &euro;4,000 a night, spend the extra ~&euro;200 and stay on the island &mdash; that's the experience you're flying to Montenegro for."),
            ("The villa isn't as private as you'd think.", "A public walking path runs directly in front of it, plus a small local road into town. Neither bothered me, but if absolute privacy is the priority, the island is still the obvious choice."),
            ("Reopening details, honestly stated.", "They're hoping to reopen around July 1 without guaranteeing the date; entry-level rooms won't be offered this season, and only 16 of the 27 Deluxe Cottages are expected initially, ranging roughly 60&ndash;100 square meters."),
            ("Fly into Tivat.", "Helicopters exist, but international arrivals still clear immigration first &mdash; it's not as seamless as the Maldives. Also note the Janu under construction next door, visible from parts of the property."),
        ],
        verdict="Everything here comes from walking the property with the GM — and if you're already spending €4,000 a night, stay on the island.",
    ),

    dict(
        slug="mamula-island-montenegro", name="Mamula Island by Banyan Tree", short_name="Mamula",
        island="Montenegro", island_page="montenegro.html", locale="Bay of Kotor, Montenegro",
        img_dir="montenegro", hero_img="mamula-fort-entrance.jpg", img2="mamula-panoramic-suite.webp",
        mailto_prep="in",
        meta_desc="Keith's firsthand, scored review of Mamula Island by Banyan Tree — a restored 19th-century fortress hotel that's more impressive as a place than as a hotel.",
        tagline="A restored 19th-century fortress at the mouth of the Bay of Kotor &mdash; extraordinary place, unfinished hotel.",
        style_label="Historic fortress hotel", perfect_for="History lovers, design travelers, one-of-a-kind stays",
        credit_label="hotel credit", partner_clause="", visited_verb="stayed at",
        region_label="Country",
        stat1_num="10/10", stat1_label="My Score: Property &amp; Atmosphere",
        stat2_num="6.5/10", stat2_label="My Overall Score",
        rank_href="montenegro.html", rank_text="Scored in my Montenegro guide",
        related_text="Read My Full Scored Review",
        cta2_href="montenegro.html", cta2_text="Montenegro, Hotel By Hotel",
        cta_island_text="My Montenegro Guide",
        intro=[
            "Mamula is a restored 19th-century fortress on a small island at the entrance to the Bay of Kotor &mdash; later a prison and concentration camp during WWII, now a luxury hotel under Banyan Tree. I booked one night in a Jr Suite with Sea View because I love history, and it's not often the history feels this central to the experience.",
            "The property is the reason to stay: arrival is by boat, the restoration is incredibly well done, and I spent most of my stay simply walking the island. I scored Property &amp; Atmosphere a 10/10 &mdash; the setting is unlike anything else I've experienced, and I appreciated that the hotel doesn't appear interested in hiding its history.",
            "The operation is another story. Service scored 6/10 &mdash; friendly but unpolished &mdash; and Food &amp; Beverage 5.5/10, the weakest part of the experience. My overall score landed at 6.5/10: far more impressive as a place than as a hotel, for now.",
        ],
        stood_out=[
            ("Stay inside the original fortress structure.", "Thick stone walls, vaulted ceilings, and the feeling of actually staying inside the fortress rather than looking at it. Entry-level rooms sit in newer construction above it &mdash; some prefer the balconies, but I want the stone."),
            ("Arrival by boat.", "The approach to the fortress sets the tone for the whole stay."),
            ("One of the most unique hotel concepts in Europe.", "Whatever you conclude about converting this history into a hotel, it's hard to argue with the singularity of the place."),
        ],
        know=[
            ("Set service expectations now.", "A ten-minute wait to be greeted at lunch, a speakeasy that was 'open' with nobody in it, a hands-off beach &mdash; individually minor, collectively they added up."),
            ("Plan around the F&amp;B gaps.", "The beach has no food or beverage outlet &mdash; roughly a ten-minute walk to the nearest one &mdash; and neither dinner nor the crudo won me over. The presentation felt basic for the price point."),
            ("The water policy is real.", "Tap water isn't drinkable and guests get one complimentary bottle per day; my second one came from the minibar, at a charge. I honestly can't remember encountering that at this level before."),
            ("My room had rough edges.", "A shower that flooded the bathroom floor and loose finish hardware &mdash; beautiful room, not a perfectly executed one."),
        ],
        verdict="With stronger service and a much better F&B program this could be one of the Mediterranean's most compelling hotels. Today, it's a 6.5/10 — an extraordinary place, not yet an extraordinary hotel.",
    ),

    dict(
        slug="one-and-only-portonovi-montenegro", name="One&amp;Only Portonovi", short_name="Portonovi",
        island="Montenegro", island_page="montenegro.html", locale="Portonovi, Montenegro",
        img_dir="montenegro", hero_img="sveti-stefan-aerial.jpg", img2="mamula-terrace-pine-tree.webp",
        mailto_prep="in",
        meta_desc="Why One&Only Portonovi is next on Keith's Montenegro inspection list — an honest advisor's take on booking it before his firsthand review lands.",
        tagline="Next up on my Montenegro list &mdash; the One&amp;Only flag at the mouth of the Bay of Kotor.",
        style_label="Marina-front resort", perfect_for="Adriatic first-timers, spa travelers, marina life",
        credit_label="hotel credit", partner_clause="", visited_verb="reviewed",
        region_label="Country",
        know_heading=ADVISOR_HEADING,
        cta_line="Portonovi is on my booking list for a reason. Let me match you to the right room, time it to the right season, and build the rest of the trip around it.",
        stat1_num="Next Up", stat1_label="In My Montenegro Guide",
        stat2_num="Fora", stat2_label="Preferred Partner Perks",
        rank_href="montenegro.html", rank_text="Next up in my Montenegro guide",
        related_text="Read My Montenegro Guide So Far",
        cta2_href="montenegro.html", cta2_text="Montenegro, Hotel By Hotel",
        cta_island_text="My Montenegro Guide",
        intro=[
            "My Montenegro guide is built one property at a time, as I actually visit &mdash; some as full stays with complete scoring, others as first looks, clearly labeled either way. One&amp;Only Portonovi is the property I've flagged as next up, which means exactly what it says: it's on my inspection list, and I haven't walked it yet.",
            "It's on my booking list anyway. Montenegro doesn't get nearly the coverage it deserves for a country with this much dramatic coastline and this few truly luxury hotels &mdash; and Portonovi is one of the flags my Adriatic clients ask about first.",
            "Until my own review lands, my clients get what they always get: Fora preferred partner amenities, my pre-arrival conversations with the on-property team, and the context of having personally stayed at and toured the country's other headline properties, <a href=\"aman-sveti-stefan-montenegro.html\">Aman Sveti Stefan</a> and <a href=\"mamula-island-montenegro.html\">Mamula Island</a>.",
        ],
        stood_out=[
            ("Why it's on my list.", "A major resort brand on a coastline with very few true luxury options &mdash; the supply-demand math alone earns it a look."),
            ("The Montenegro context I already have.", "Having scored Mamula as a guest and toured Aman Sveti Stefan with its GM, I know exactly what the local bar is &mdash; and where it isn't being met."),
            ("The honest-guide format.", "When I do visit, Portonovi gets the same treatment as the others: full scoring, no press materials, clearly labeled."),
        ],
        know=[
            ("I haven't visited yet.", "That's stated plainly in my <a href=\"../montenegro.html\">Montenegro guide</a> &mdash; the same guide where I publish complete scores when I have them."),
            ("Fly into Tivat.", "The same arrival advice I give for the whole coast: international arrivals clear immigration before any onward transfer."),
            ("Building a full Adriatic trip?", "I pair Montenegro's hotels hotel-by-hotel &mdash; tell me your dates and I'll tell you honestly which property earns which nights."),
        ],
        verdict="Next up in my guide, on my booking list today — and when I've walked it, you'll get the full scored review, not a brochure.",
    ),

    # ------------------------------------------------------------------ FRANCE
    dict(
        slug="zannier-ile-de-bendor-france", name="Zannier H&ocirc;tels &Icirc;le de Bendor", short_name="&Icirc;le de Bendor",
        island="Provence", island_page="destination-guides.html", locale="Bandol, France",
        img_dir="bendor", hero_img="bendor-hero.jpg", img2="bendor-village-harbor.jpg",
        mailto_prep="in",
        meta_desc="Keith's guide to Zannier Hôtels Île de Bendor — Paul Ricard's private island off Bandol, reimagined as a one-of-a-kind Riviera resort.",
        tagline="A five-minute boat ride, a world away &mdash; Paul Ricard's private island, reimagined by Zannier.",
        style_label="Private island resort", perfect_for="Couples, Riviera romantics, slow travel",
        credit_label="$100 USD equivalent food &amp; beverage credit", partner_clause="", visited_verb="featured",
        region_label="Region",
        know_heading=ADVISOR_HEADING,
        cta_line="&Icirc;le de Bendor is a featured property on my list for a reason. Let me match you to the right suite, time it to the right season, and build the rest of the Riviera trip around it.",
        stat1_num="2", stat1_label="Garden Villages: Delos &amp; Soukana",
        stat2_num="0", stat2_label="Cars On The Island",
        rank_href="zannier-ile-de-bendor.html", rank_text="My featured-property page",
        related_text="Read My Full &Icirc;le de Bendor Feature",
        cta2_href="top-hotel-pools.html", cta2_text="My Favorite Hotel Pools",
        cta_island_text="All My Destination Guides",
        intro=[
            "Just off the coast of Bandol on the French Riviera sits a tiny private island with an outsized history. &Icirc;le de Bendor was once the personal retreat of pastis magnate Paul Ricard, who spent decades filling it with gardens, art, and a distinctly southern-French sense of leisure.",
            "Zannier Hotels has reimagined the entire island as a one-of-a-kind resort &mdash; honey-stone villages, a working harbor, a spa built into the rock, and some of the best sunset views on the C&ocirc;te d'Azur. The island unfolds across two garden villages, Delos and Soukana, each with its own pool and its own personality, connected by footpaths and electric buggies.",
            "It's a featured property on my list, and the kind of booking where the details matter: the right village, the right suite, and the right season change the entire experience. That's what I handle.",
        ],
        stood_out=[
            ("Three rooms worth knowing.", "The Delos Pavilion Suite, with arched windows opening straight onto the sea; the warmer, residential Soukana Terrace Junior Suite in the gardens; and The Delos Suite &mdash; the island's most private terrace, with an outdoor soaking tub under the lemon trees."),
            ("The R&#275;sonance Wellness Centre.", "A spiral stone staircase drops straight into a plunge pool, with a second courtyard pool, treatment rooms, and a tea room above."),
            ("Sunset at Le Grand Large, apéro at Bar Patrick.", "Cliffside tables for sunset, a yacht-club dining room at La Table Delos for everything else, and a hand-tiled bar built for a slow pastis at golden hour."),
            ("No cars, by design.", "Electric 'Mini Kate' buggies shuttle guests between villages, the harbor, and the pools."),
        ],
        know=[
            ("Pick your village deliberately.", "Delos puts you on the water; Soukana is quieter, tucked into the gardens near the pine groves. Couples who want to wake up to water on both sides should ask me for the Delos Pavilion Suite."),
            ("The perks are specific here.", "Booking through me adds an upgrade on arrival and early check-in/late check-out (both subject to availability), plus a $100 USD equivalent food &amp; beverage credit &mdash; breakfast is already included in the property's rates."),
            ("It's a boat-access island.", "Five minutes from Bandol &mdash; easy, but worth building your Riviera routing around rather than treating as a drive-up hotel."),
        ],
        verdict="A one-of-a-kind private island on the Côte d'Azur — the featured property I reach for when clients want the Riviera without the scene.",
    ),
]
